import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css"
import BottomFrame from "@/components/shared/BottomFrame";
import TopFrame from "@/components/shared/TopFrame";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="w-full h-[100vh] flex items-center justify-center bg-black">
    <div className="max-w-screen-xs w-full h-full bg-white flex flex-col justify-between bg-[url('/BG.png')] bg-no-repeat bg-cover bg-center gap-3">
      <TopFrame/>
    {children}

      <BottomFrame/>
    </div>
  </div>

        
        </body>
    </html>
  );
}
