import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ThirdAppProvider from "@/providers/ThirdAppProvider";
import AppProvider from "@/contexts/AppContext";
import localFont from "next/font/local";



const inter = Inter({ subsets: ["latin"] });

const tinyUnicode = localFont({
  src: "../../fonts/TinyUnicode.ttf",
  variable: "--font-tiny-unicode",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Raigotchi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tinyUnicode.variable}  antialiased`}>
        <ThirdAppProvider>
          <AppProvider>
            
              {children}
       
          </AppProvider>
        </ThirdAppProvider>
      </body>
    </html>
  );
}
