import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const tinyUnicode = localFont({
  src: "../../../fonts/TinyUnicode.ttf",
  variable: "--font-tiny-unicode",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Raigotchi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tinyUnicode.variable}  antialiased`}>

        <div className="w-full h-[100vh] flex items-center justify-center bg-black">
        <div className="max-w-screen-xs w-full h-full bg-white flex flex-col justify-between bg-[url('/BG.png')] bg-no-repeat bg-cover bg-center gap-3 font-[family-name:var(--font-tiny-unicode)] text-white">
          {children}
        </div>
        </div>
       
      </body>
    </html>
  );
}
